### ISSUE TITLE
Unable to build solution: This specific WebPublishMethod(FileSystem) is not yet supported on msbuild command line

### ISSUE THREAD

**Issue by sshushliapin** [Sitecore/Helix.Examples#66]
Clone the repo, open [Helix Basic Unicorn solution](https://github.com/Sitecore/Helix.Examples/tree/master/examples/helix-basic-unicorn) in the Visual Studio and try to build it. Build fails:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Target WebFileSystemPublish Failed	Website			
Severity	Code	Description	Project	File	Line	Suppression State
Error		This specific WebPublishMethod(FileSystem) is not yet supported on msbuild command line.  Please use Visual Studio to publish.	Website			
```

It should not fail. It should not require any setup steps (except probably nuget restore) to _build_ the solution.

[VS2017/19]

**Comment by nickwesselman** [comment]
Hmm maybe [due to the `publishUrl` being missing](https://stackoverflow.com/a/46120861/201808) since the install/setup configures it in `Local.pubxml.user.props`, and HPP is set to auto-publish. Might need to add a default `publishUrl` or see if HPP can be configured to only auto-publish if that prop is configured.

Thanks for reporting.

**Comment by nickwesselman** [comment]
@sshushliapin This should now be resolved.
