### ISSUE TITLE
Error: Sitecore is configured for Item Serialization but the project is using Yaml

### ISSUE THREAD

**Issue by sshushliapin** [Sitecore/Helix.Examples#88]
I've got TDS version up and running using default [docker images](https://github.com/Sitecore/docker-images) and [TDS guide for containers](https://hedgehogdevelopment.github.io/tds/chapter8.html). An attempt to sync items leads to the following error. Sorry, I do not know why the window is corrupted like that... It's quite hard to read error messages sometimes:

![image](https://user-images.githubusercontent.com/4719165/80971825-fd21b400-8e25-11ea-9311-e933593a1d6b.png)

The error appears because this repo is configured to use [YAML format](    https://github.com/Sitecore/Helix.Examples/blob/master/examples/helix-basic-tds-consolidated/TdsGlobal.config#L5) but Sitecore still uses 'old good' serialization OOTB.

In order to fix that, the following setting needs to be changed on the project level:

```xml
<setting name="Serialization.SerializationType" set:value="yaml" />
```

Should I come up with a PR for that?

**Comment by nickwesselman** [comment]
We ran into a bit of a chicken-and-egg problem with that configuration and the TDS build, thus the inclusion of it in the SIF install:
https://github.com/Sitecore/Helix.Examples/blob/master/examples/helix-basic-tds/build/config/build-and-sync.json#L39

If you have a solution that works across SIF and containers, would definitely be open to a PR. Otherwise I think this configuration would need to be included in your Dockerfile?

**Comment by sshushliapin** [comment]
I guess a config file with patch would work for both... I didn't know this setting can be set via SIF. If SIF is the default installation option for this repo then probably it makes sense to leave it as it is right now.

**Comment by nickwesselman** [comment]
It's actually a custom SIF task (there are a few of those in this solution). It does deploy a config file patch, but there was an issue with the timing of the deployment of that patch in the TDS-based solution.
