### ISSUE TITLE
Proper order of operations for adding a project?

### ISSUE THREAD

**Issue by benjaminhigginsliquid** [Sitecore/Helix.Examples#90]
I see that Helix Base and this repository both share in the same conceptual IDE setup, so with that in mind I'm posing my question here as it pertains to both. How are developers expected to add new projects to a Visual Studio setup like this? 

The requirements based on the existing projects and the Directory.Build.Props file indicate that we are to create projects whose .csproj file lives directly under folders called "website", under folders within their related Helix pillar, (arbitrarily) titled in the format {Pillar.ProjectName},

My common intuition tells me to do the following after observing the existing structure: 

1. Create a physical folder directly under Feature: "MyProject", 
2. Add a "MyProject" solution folder to mimic the same structure within Visual Studio. 
3. Right click on this solution folder, add new project, and set the Location to the MyProject physical folder created in step 1

At this point I've hit my first problem; whatever I name the project, will become the name of the folder. There is no Visual Studio 2019 option I am aware of that lets you specify that you wish to ether create a project (AKA place the csproj) directly into an existing folder, or name the created folder something other than the project.

If I decided I would just name the project "website", so that the folder is made, then rename it post-creation, I run into a second problem: Visual Studio believes a project named "website" already exists. The details of why this is happening is not something I have research, but this seems to be a prevalent "issue" in Visual Studio that has persisted for several years but has never accrued enough interest to warrant a fix.

Ultimately, the only solution we've found to actually work is to copy an existing project and manually adjust several folders and csproj values, which feels counter-intuitive to any developer we would like to be able to "plug and dev".

Please let me know what the expected order of operations here are for performing this common dev task, as the Helix conventions indirectly encourage lots of projects by way of highly module design, but the overhead for any developer to figure out how to create a project (and ensure that they created it properly) currently seems egregious.

**Comment by nickwesselman** [comment]
@benjaminhigginsliquid Sorry for the delayed reply.

Helix does add some overhead in this respect, but I would be careful about saying that *Helix conventions indirectly encourage lots of projects*. Helix conventions encourage projects that separate business domains. Too often I've seen Helix projects that have [too many projects](https://helix.sitecore.net/appendix/alternate-visual-studio-structures.html#are-your-modules-too-granular), because they are applying atomic design to Helix structure or otherwise breaking things down too much.

That said, when you do need to create a new project, one option is community tools like [Helix VS Templates](https://github.com/LaubPlusCo/LaubPlusCo.Helix.VsTemplates) and [Helix Generator](https://www.npmjs.com/package/generator-helix).

When I need to do it manually, it's a little involved but my process is something like this:

1. In the appropriate solution folder, *Add > New Project* and select *ASP.NET Web Application (.NET Framework)*
1. Name the project `BasicCompany.Feature.[Name].Website`
1. Place the project on the filesystem in `src\Feature\[Name]`
1. Click *Create*
1. Select an *Empty* project and uncheck *Configure for HTTPS*
1. Click *Create*
1. Immediately remove the project from the solution
1. Rename the created project folder `src\Feature\[Name]\BasicCompany.Feature.[Name].Website` to `website`.
1. *Add* > *Existing Project* to add the project back to the appropriate solution folder
1. Select the `Web.config` and set the *Build Action* to *None*
1. Delete the `packages.config` (because I'll want to use `PackageReference`)
1. Go to the project properties and change the *Assembly name* and *Default namespace* to `BasicCompany.Feature.[Name]`
1. Unload the project and edit its `.csproj`.
    * You can add `PackageReference` for common assemblies you might need:
        ```
        <PackageReference Include="Sitecore.Kernel" Version="9.3.0" />
        <PackageReference Include="Sitecore.Mvc" Version="9.3.0" />
        ```
    * You may want to remove references to the `packages` folder, `EnsureNuGetPackageBuildImports`, references you don't need, etc.

Especially once you start adding references, moving to `PackageReference`, etc etc, you'll definitely benefit from some sort of templating tool.
