### ISSUE TITLE
Build for IIS host or Folder deployment 

### ISSUE THREAD

**Issue by MortazaKamalNourestani** [Sitecore/Helix.Examples#95]
I don't see any Build for IIS or folder deploy other than Docker?

**Comment by nickwesselman** [comment]
Hi @MortazaKamalNourestani,

With the release of Sitecore 10, we moved Helix Examples to a Docker-only build, given that they are intended to be examples of solution architecture / Sitecore development, and they are not intended to deploy into "production." You can reference [previous releases](https://github.com/Sitecore/Helix.Examples/releases) which deployed to a local install (and even managed the SIF install for you). The current examples actually have a "folder deploy" built-in still -- they just point at a folder which syncs into Docker instead of the web root.

Can I ask what your use case is which leads you to require a local deploy?

**Comment by MortazaKamalNourestani** [comment]
@nickwesselman thank you for the reply.

I am trying to adapt towards Helix converting some of the projects that I inherited and I am testing locally on IIS. Not all companies want to use docker and many of clients don't even host on Could due to many reasons.

I know it is just an example but there is a huge confusion towards 2 areas that since I have worked with Sitecore 5 it has not been very straight forward and it looks like we circling back to the same issue namely Installation and Deployment. Each of these so called Helix examples are using different approach Gulp Cake PS and some other ways but no unified approach and Sitecore not the best example on "How To Install" it is just as if they are stuck in that and never made it further. Even Win10 as OS is much simpler to install and is getting much more simpler with each release. Is SC more complicated than Win10?

**Comment by nickwesselman** [comment]
Hi @MortazaKamalNourestani -- The installation/deployment method is really a small part when it comes to your Helix solution architecture. It sounds like you are specifically struggling with what approach to use for the build of your solution. Each organization has their own requirements, expertise, and toolset. The examples within show both use of TDS and Helix Publishing Pipeline, which both make it fairly simple to combine the output of multiple web application projects. The old Habitat used Gulp, which not many .NET developers were fans of, but may be a fit for organizations which wish to integrate their front-end build processes as well. Others with more complex build and deployment requirements and a .NET focus prefer Cake. Sitecore Helix itself aims to be tool agnostic.

Sorry perhaps not the answer you were looking for!
